config/routes.rb
Rails.application.routes.draw do
   require 'sidekiq/web'
  devise_for :users
   root 'products#index'
   resources :products do
      resources :carts
   end
   resources :carts
   get '/total_bill', to: 'carts#total_bill'
   post '/place_order', to: 'carts#place_order'
   get '/confirm_order', to: 'carts#confirm_order'
   mount Sidekiq::Web => '/sidekiq'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

def initialize(user)
alias_action :create, :read, :update, :destroy, :to => :crud
 
  
  if user.admin?
      can :crud, Product  # Admin can manage (create, read, update, delete) products
  else
      can :manage, Cart
      can :read, Product  # Regular customers can only read products
  end
end

  
end
 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
  
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :product
  belongs_to :user
end

app/models/product.rb
class Product < ApplicationRecord
has_many :carts
has_many :users , through: :carts
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable , :confirmable


has_many :carts
has_many :products, through: :carts



 enum :role, { customer: 0, admin: 1}
 def admin? 
  role== "admin"
end 

def customer? 
  role== "customer"
end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
before_action :find_user

def index
@carts=Cart.all
end


def total_bill
    @carts = current_user.carts
    @total_bill = @carts.sum(:bill)
end


def place_order

  @carts = current_user.carts
  @cart = @carts.last
  # OrderMailer.order_confirmation_email(current_user,@cart).deliver_now
  MyFirstJob.perform_in(1.minutes, current_user.id, @cart.id)
 redirect_to total_bill_path, notice: 'Please click the link from your mail to confirm the order'
end



def confirm_order
 carts=current_user.carts
 carts.destroy_all
end




def create
   
 @cart = current_user.carts.build(cart_params)
  @product = Product.find(params[:product_id])

  @cart.bill = @cart.quantity * @product.price

  @cart.token = SecureRandom.urlsafe_base64
    if @cart.save
      redirect_to cart_path(@cart), notice: "Cart was successfully created."
    else
      render 'new'
    end
  end

  


  def show
    @cart = Cart.find(params[:id])
  end

  def new
    @cart=Cart.new
    @cart.product_id=params[:id]
  end


 private
    def cart_params

      params.require(:cart).permit(:quantity,:product_id,:user_id,:token)
    end

    def find_user
      @user ||= User.find_by(id:params[:user_id])
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  load_and_authorize_resource
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
    authorize! :show, @product
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to @product
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])

    if @product.update(product_params)
      redirect_to @product
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_url, notice: 'Product was successfully destroyed.'
  end

  private

  def product_params
    params.require(:product).permit(:name, :description, :price)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/carts/confirm_order.html.erb
<h1>Congratulations ! </h1>
<p>Your order has been successfully placed.</p>
 <h4><%= link_to "Buy More Products", products_path %></h4>

app/views/carts/show.html.erb
<h1><%= @cart.product.name %></h1>
<p><strong>Cart_Id:</strong> <%= @cart.id %></p>
<p><strong>Product Name:</strong> <%= @cart.product.name %></p>
<p><strong>Bill:</strong> <%= @cart.bill %></p>
<br>
<br>
<div>
    <%= link_to 'Total Bill', total_bill_path %>
 </div>

app/views/carts/total_bill.html.erb
<h1>Total Bill</h1>
<% if @carts.any? %>
  <ul>
    <% @carts.each do |cart| %>
      <li>
        <strong>Item:</strong> <%= cart.product.name %><br>
        <strong>Bill:</strong> <%= cart.bill %><br>
        <strong>Quantity:</strong> <%= cart.quantity %>
      </li>
    <% end %>
  </ul>
  <p><strong>Total Bill:</strong> <%= @total_bill %></p>
<% else %>
  <p>No carts found.</p>
<% end %>

<%= form_tag place_order_path, method: :post do %>
  <%= submit_tag 'Place Order', data: { confirm: 'Are you sure you want to place the order?' } %>
<% end %>
<%= link_to 'Buy New Products', products_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProductManagmentSystem</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
     <style>
    .navbar {
      background-color: #007bff;
      padding: 10px;
      color: #ffffff;
      text-align: center;
    }

    .navbar a {
      color: #ffffff;
      text-decoration: none;
      margin: 0 15px;
      font-size: 18px;
    }

    .navbar-dropdown {
      display: inline-block;
    }
 .navbar-dropdown1 {
      display: inline-block;
    }
    .dropdown-content {
      display: none;
      position: absolute;
      background-color: #f9f9f9;
      min-width: 160px;
      box-shadow: 0 8px 16px rgba(0,0,0,0.2);
      z-index: 1;
    }
    .dropdown-content1 {
      display: none;
      position: absolute;
      background-color: #f9f9f9;
      min-width: 160px;
      box-shadow: 0 8px 16px rgba(0,0,0,0.2);
      z-index: 1;
    }

    .dropdown-content a {
      color: #333;
      padding: 12px 16px;
      text-decoration: none;
      display: block;
    }

    .dropdown-content1 a {
      color: #333;
      padding: 12px 16px;
      text-decoration: none;
      display: block;
    }

    .dropdown-content a:hover {
      background-color: #ddd;
    }
.dropdown-content1 a:hover {
      background-color: #ddd;
    }
    .navbar-dropdown:hover .dropdown-content {
      display: block;
    }
    .navbar-dropdown1:hover .dropdown-content1 {
      display: block;
    }
  </style>
  </head>

  <body>
    <div class="navbar">
  <% unless current_user&.admin? %>
  <div class="navbar-dropdown1">
    <a href="#">Cart</a>
    <div class="dropdown-content1">
      <%= link_to 'Total Bill', total_bill_path %>
    </div>
  </div>
<% end %>


  <% if user_signed_in? %>
    <div class="navbar-dropdown">
      <a href="#">Current User</a>
      <div class="dropdown-content">
        <a href="#">Sign in as <%= current_user.email %></a>
        <%= button_to 'Sign Out', destroy_user_session_path, method: :delete %>
      </div>
    </div>
  <% end %>
</div>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

  </body>
</html>

app/views/products/edit.html.erb
     <h1>Edit The Product</h1>
<%= form_with model: @product do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :price %><br>
    <%= form.number_field :price, step: '0.01' %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/products/index.html.erb
<h1>All Grocery Products in the store</h1>

<ul>
  <% @products.each do |product| %>
    <li>
      <%= link_to product.name, product %>
    </li>
  <% end %>
</ul> 

<% if can? :create, Product %>
  <%= link_to 'New Product', new_product_path %>
<% end %>

app/views/products/new.html.erb
     <h1>New Product</h1>
<%= form_with model: @product do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :price %><br>
    <%= form.number_field :price, step: '0.01' %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>
<%= link_to 'Back', products_path %> 

app/views/products/show.html.erb
<h1><%= @product.name %></h1>
<p><strong>Description:</strong> <%= @product.description %></p>
<p><strong>Price:</strong> <%= number_to_currency(@product.price) %></p>

<%= link_to 'Back', products_path %> <br><br>

<% if can? :update, @product %>
  <strong><%= link_to 'Edit', edit_product_path(@product) %></strong><br><br>
<% end %>

<% if can? :destroy, @product %>
  <strong><%= link_to "Destroy", product_path(@product), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></strong>
<% end %>

<% if can? :manage, Cart %>
<h2>Add To Cart:</h2>
<%= form_with(model: [@product, @product.carts.build]) do |form| %>
  <p>
    <%= form.label :quantity %><br>
    <%= form.text_field :quantity %>
  </p>
  
  <%= form.hidden_field :product_id, value: @product.id %>
  <%= form.hidden_field :user_id, value: current_user.id %> 
  
  <div>
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Back', products_path %> <br><br>
<% end %>